#   已检异常和未检异常

Java 的异常处理机制会区分两种不同的异常类型： 已检异常和未检异常

已检异常和未检异常之间的区别在于异常在什么情况下抛出。 已检异常在明确的特定情况下抛出，经常是应用能部分或完全恢复的情况。

例如，试图打开的文件不在某个目录下，会抛出 FileNotFoundException 异常，可以捕获这个异常然后在文件可能出现的下一个位置继续尝试。也就是说，虽然文件不存在是异常状况，但可以从中恢复，这是意料之中的失败。

Java 环境中有些失败是无法预料的，这些失败可能是由运行时条件或滥用库代码导致的。例如，无法正确预知 OutOfMemoryError 异常，把无效的 null 传给使用对象或数组的方法，会抛出 NullPointerException 异常。

这些是未检异常，基本上任何方法在任何时候都可能抛出未检异常。这是 Java 环境中的墨菲定律： "会出错的事总会出错"，从未检异常中恢复，虽说不是不可能，但往往很难，因为完全不可预知。

异常是 Throwable 对象，而且异常主要分为两类：Error 和 Exception 子类标识。只要异常对象是 Error 类，就是未检异常。 Exception 类的子类 RuntimeException 的所有子类都属于未检异常，除此之外，都是已检异常。

##  处理已检异常

Java 为 已检异常和未检异常 指定了不同的规则。

如果定义的方法会抛出已检异常，就必须在方法签名的 throws 子句中声明这个异常。

就算自己从不抛出已检异常，有时也必须使用 throws 子句声明已检异常。如果方法中调用了会抛出已检异常的方法，要么加入异常处理代码处理这个异常，要么使用 throws 子句声明这个方法也能抛出这个异常。

----